version: "3"

networks: 
  drivenops_backend:
    driver: bridge

volumes: 
  pg_drivenops:
  react_drivenops:

services:
  db_postgres:
    image: postgres:13
    container_name: db_postgres_drivenops
    restart: always 
    ports:
      - 2345:5432
    networks:
      - drivenops_backend
    volumes:
      - pg_drivenops:/var/lib/postgresql/data
    env_file:
      - back-end/.env

  node_app:
    container_name: node_app_drivenops
    build: back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    networks:
      - drivenops_backend
    env_file:
      - back-end/.env

  app_react:
    build: front-end
    container_name: app_react_drivenops
    networks:
      - drivenops_backend
    volumes:
      - react_drivenops:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx_drivenops
    ports:
      - 80:80
    networks:
      - drivenops_backend
    volumes:
      - react_drivenops:/var/www/html
    depends_on:
      - app_react
      - node_app
  
