version: "3"

networks: 
  drivenops_backend:
    driver: bridge

volumes: 
  pg_drivenops:

services:
  db_postgres:
    image: postgres:13
    container_name: db_postgres_drivenops
    restart: always 
    ports:
      - 2345:5432
    networks:
      - drivenops_backend
    volumes:
      - pg_drivenops:/var/lib/postgresql/data
    env_file:
      - back-end/.env

  node_app:
    container_name: node_app_drivenops
    build: back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    networks:
      - drivenops_backend
    env_file:
      - back-end/.env
  
