name: PullRequest

on: [pull_request]

jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students"
          envkey_DATABASE_URL: "postgres://postgres:postgres@db_postgres_drivenops:5432/students"
          directory: back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
      - name: Build
        run: npm i && npm run build